### ISSUE TITLE
Dockerfile does not build because of scoutbot dependency, which can be installed on its own.

### ISSUE THREAD

**Issue by bw4sz** [WildMeOrg/scout#76] opened 2024-03-29 14:36 UTC
This was my first try with scout to get a sense for its functionalities and ability for my team to extend the code base. For that reason I went to the repo and not dockerhub. I was unable to build the dockerfile because of scoutbot installation.

# Reproduce

Start docker and run
```
git clone https://github.com/WildMeOrg/scout.git
cd scout
docker build .
```

yields

```
(base) benweinstein@Bens-MacBook-Pro scout % docker build .
[+] Building 254.8s (10/40)                                                                                 docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                        0.0s
 => => transferring dockerfile: 1.59kB                                                                                      0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04                                    2.4s
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                                                                  0.0s
 => [internal] load .dockerignore                                                                                           0.0s
 => => transferring context: 80B                                                                                            0.0s
 => [ 1/35] FROM docker.io/nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04@sha256:ea2af6ed2bc770f83ed30235f7369b8c83a49b58c  97.8s
 => => resolve docker.io/nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04@sha256:ea2af6ed2bc770f83ed30235f7369b8c83a49b58cdb0  0.0s
 => => sha256:5971243731bceb03735002e6ee458efdf4a5bb61dc9413e66c37f9d600f0747f 12.66kB / 12.66kB                            0.0s
 => => sha256:ea2af6ed2bc770f83ed30235f7369b8c83a49b58cdb0bfd55f1227d89edfad8f 743B / 743B                                  0.0s
 => => sha256:a3d20efe6db8b46becf9f41b997b53a8b8165d6bfeee0a5ff49a7be97bdf2233 7.94MB / 7.94MB                              2.2s
 => => sha256:56480238c4d714e5e5d2438e34e144c114a8d1088c5f385b791bab68b7f3ccdc 2.42kB / 2.42kB                              0.0s
 => => sha256:96d54c3075c9eeaed5561fd620828fd6bb5d80ecae7cb25f9ba5f7d88ea6e15c 27.51MB / 27.51MB                            2.1s
 => => sha256:bfdf8ce43b671936d3ff95ddbbf98c7e5a6fcf9c30b391ff68a1f5bd8f2542f0 23.61MB / 23.61MB                            4.6s
 => => sha256:ad14f66bfcf925d4d3845f273afe5a865b9d9e9facf722b88416b30ac62071a0 184B / 184B                                  2.4s
 => => sha256:1056ff735c5934cffc31a621d8f362eb3ecaee0667227fe735dfaaa1165286f3 6.88kB / 6.88kB                              2.4s
 => => extracting sha256:96d54c3075c9eeaed5561fd620828fd6bb5d80ecae7cb25f9ba5f7d88ea6e15c                                   1.7s
 => => sha256:a08e157987cd9fc3e8d38ceeaf215714d570bd31c907f95789149406cf533488 1.12GB / 1.12GB                             64.1s
 => => sha256:b05f735a8d36dd8deb11dd6429ceadd62dc9e4a39853b522a52ba8d81cde20ec 62.69kB / 62.69kB                            3.1s
 => => sha256:2ca2acc6de6fb15b50b8fb872e242fd21a9aab9ebb28e6438f5f2d4f99f601e1 1.68kB / 1.68kB                              3.3s
 => => sha256:a5f96919abbf7212577a68604528951c76e98558582f83236e7e6f0fb2a24f54 1.52kB / 1.52kB                              3.6s
 => => sha256:e2656b42ba8bbb33ae9842d877d83f583017e58fc1b7ebbcdf97e42dc654a408 727.16MB / 727.16MB                         37.7s
 => => extracting sha256:a3d20efe6db8b46becf9f41b997b53a8b8165d6bfeee0a5ff49a7be97bdf2233                                   0.4s
 => => extracting sha256:bfdf8ce43b671936d3ff95ddbbf98c7e5a6fcf9c30b391ff68a1f5bd8f2542f0                                   0.6s
 => => extracting sha256:ad14f66bfcf925d4d3845f273afe5a865b9d9e9facf722b88416b30ac62071a0                                   0.0s
 => => extracting sha256:1056ff735c5934cffc31a621d8f362eb3ecaee0667227fe735dfaaa1165286f3                                   0.0s
 => => extracting sha256:a08e157987cd9fc3e8d38ceeaf215714d570bd31c907f95789149406cf533488                                  20.5s
 => => extracting sha256:b05f735a8d36dd8deb11dd6429ceadd62dc9e4a39853b522a52ba8d81cde20ec                                   0.0s
 => => extracting sha256:2ca2acc6de6fb15b50b8fb872e242fd21a9aab9ebb28e6438f5f2d4f99f601e1                                   0.0s
 => => extracting sha256:a5f96919abbf7212577a68604528951c76e98558582f83236e7e6f0fb2a24f54                                   0.0s
 => => extracting sha256:e2656b42ba8bbb33ae9842d877d83f583017e58fc1b7ebbcdf97e42dc654a408                                  12.9s
 => [internal] load build context                                                                                           1.3s
 => => transferring context: 108.28MB                                                                                       1.3s
 => [ 2/35] RUN set -ex  && apt-get update  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends   28.2s
 => [ 3/35] RUN apt-get -y update                                                                                           5.1s
 => [ 4/35] RUN apt-get -y install git                                                                                      7.8s
 => ERROR [ 5/35] RUN pip install git+https://github.com/WildMeOrg/scoutbot.git                                           112.9s
------
 > [ 5/35] RUN pip install git+https://github.com/WildMeOrg/scoutbot.git:
1.016 Collecting git+https://github.com/WildMeOrg/scoutbot.git
1.017   Cloning https://github.com/WildMeOrg/scoutbot.git to /tmp/pip-req-build-9zppw5h6
1.017   Running command git clone -q https://github.com/WildMeOrg/scoutbot.git /tmp/pip-req-build-9zppw5h6
2.433   Installing build dependencies: started
6.402   Installing build dependencies: finished with status 'done'
6.407   Getting requirements to build wheel: started
6.623   Getting requirements to build wheel: finished with status 'done'
6.627     Preparing wheel metadata: started
6.824     Preparing wheel metadata: finished with status 'done'
7.378 Collecting gradio
7.430   Downloading gradio-4.24.0-py3-none-any.whl (17.1 MB)
8.663 Collecting codecov
8.679   Downloading codecov-2.1.13-py2.py3-none-any.whl (16 kB)
8.804 Collecting wbia-utool
8.903   Downloading wbia_utool-4.0.4-py3-none-any.whl (581 kB)
9.058 Collecting pooch==1.8.0
9.077   Downloading pooch-1.8.0-py3-none-any.whl (62 kB)
10.92 Collecting coverage
11.00   Downloading coverage-7.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (234 kB)
11.24 Collecting sahi
11.26   Downloading sahi-0.11.15-py3-none-any.whl (105 kB)
11.89 Collecting opencv-python-headless==4.7.0.68
12.04   Downloading opencv_python_headless-4.7.0.68-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.2 MB)
18.03 Collecting dill==0.3.7
18.04   Downloading dill-0.3.7-py3-none-any.whl (115 kB)
18.29 Collecting torchvision
18.35   Downloading torchvision-0.17.2-cp38-cp38-manylinux1_x86_64.whl (6.9 MB)
18.94 Collecting click
18.95   Downloading click-8.1.7-py3-none-any.whl (97 kB)
19.21 Collecting rich
19.23   Downloading rich-13.7.1-py3-none-any.whl (240 kB)
19.61 Collecting ultralytics
19.62   Downloading ultralytics-8.1.37-py3-none-any.whl (723 kB)
20.55 Collecting cryptography
20.57   Downloading cryptography-42.0.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
21.05 Collecting imgaug
21.07   Downloading imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
21.95 Collecting Pillow
22.01   Downloading pillow-10.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
22.57 Collecting onnxruntime
22.58   Downloading onnxruntime-1.16.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.4 MB)
23.35 Collecting tqdm
23.36   Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
23.53 Collecting sphinx-click
23.59   Downloading sphinx_click-5.1.0-py3-none-any.whl (9.7 kB)
24.58 Collecting numpy
24.64   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
26.32 Collecting torch
26.33   Downloading torch-2.2.2-cp38-cp38-manylinux1_x86_64.whl (755.5 MB)
78.66 Collecting markupsafe~=2.0
78.69   Downloading MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
78.74 Collecting python-multipart>=0.0.9
78.75   Downloading python_multipart-0.0.9-py3-none-any.whl (22 kB)
78.85 Collecting gradio-client==0.14.0
78.86   Downloading gradio_client-0.14.0-py3-none-any.whl (312 kB)
79.11 Collecting fastapi
79.17   Downloading fastapi-0.110.0-py3-none-any.whl (92 kB)
79.29 Collecting tomlkit==0.12.0
79.30   Downloading tomlkit-0.12.0-py3-none-any.whl (37 kB)
79.37 Collecting typing-extensions~=4.0
79.39   Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
79.43 Collecting ffmpy
79.44   Downloading ffmpy-0.3.2.tar.gz (5.5 kB)
79.96 Collecting jinja2<4.0
79.97   Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
80.48 Collecting pydantic>=2.0
80.60   Downloading pydantic-2.6.4-py3-none-any.whl (394 kB)
80.83 Collecting uvicorn>=0.14.0; sys_platform != "emscripten"
80.85   Downloading uvicorn-0.29.0-py3-none-any.whl (60 kB)
81.02 Collecting huggingface-hub>=0.19.3
81.03   Downloading huggingface_hub-0.22.2-py3-none-any.whl (388 kB)
81.32 Collecting packaging
81.34   Downloading packaging-24.0-py3-none-any.whl (53 kB)
81.40 Collecting aiofiles<24.0,>=22.0
81.42   Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
82.06 Collecting pandas<3.0,>=1.0
82.07   Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
83.81 Collecting httpx>=0.24.1
83.88   Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
84.03 Collecting importlib-resources<7.0,>=1.3
84.05   Downloading importlib_resources-6.4.0-py3-none-any.whl (38 kB)
84.23 Collecting pyyaml<7.0,>=5.0
84.25   Downloading PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)
84.43 Collecting semantic-version~=2.0
84.45   Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
86.30 Collecting ruff>=0.2.2; sys_platform != "emscripten"
86.32   Downloading ruff-0.3.4-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.7 MB)
87.72 Collecting matplotlib~=3.0
87.75   Downloading matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
88.64 Collecting typer[all]<1.0,>=0.9; sys_platform != "emscripten"
88.66   Downloading typer-0.11.1-py3-none-any.whl (43 kB)
88.89 Collecting pydub
88.99   Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
89.06 Collecting altair<6.0,>=4.2.0
89.13   Downloading altair-5.2.0-py3-none-any.whl (996 kB)
90.52 Collecting orjson~=3.0
90.53   Downloading orjson-3.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
90.66 Collecting requests>=2.7.9
90.73   Downloading requests-2.31.0-py3-none-any.whl (62 kB)
90.90 Collecting pint
90.92   Downloading Pint-0.21.1-py3-none-any.whl (290 kB)
91.00 Collecting lockfile
91.09   Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
91.24 Collecting six
91.25   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
91.44 Collecting pyparsing
91.45   Downloading pyparsing-3.1.2-py3-none-any.whl (103 kB)
91.57 Collecting gitpython
91.59   Downloading GitPython-3.1.42-py3-none-any.whl (195 kB)
91.82 Collecting networkx
91.84   Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
92.35 Collecting ubelt
92.37   Downloading ubelt-1.3.5-py3-none-any.whl (224 kB)
93.25 Collecting psutil
93.32   Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
93.39 Collecting delorean
93.41   Downloading Delorean-1.0.0.tar.gz (18 kB)
93.73 Collecting parse
93.83   Downloading parse-1.20.1-py2.py3-none-any.whl (20 kB)
94.37 Collecting opencv-contrib-python-headless
94.39   Downloading opencv_contrib_python_headless-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (55.7 MB)
112.5 ERROR: Exception:
112.5 Traceback (most recent call last):
112.5   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/response.py", line 425, in _error_catcher
112.5     yield
112.5   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/response.py", line 507, in read
112.5     data = self._fp.read(amt) if not fp_closed else b""
112.5   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 62, in read
112.5     data = self.__fp.read(amt)
112.5   File "/usr/lib/python3.8/http/client.py", line 459, in read
112.5     n = self.readinto(b)
112.5   File "/usr/lib/python3.8/http/client.py", line 503, in readinto
112.5     n = self.fp.readinto(b)
112.5   File "/usr/lib/python3.8/socket.py", line 669, in readinto
112.5     return self._sock.recv_into(b)
112.5   File "/usr/lib/python3.8/ssl.py", line 1270, in recv_into
112.5     return self.read(nbytes, buffer)
112.5   File "/usr/lib/python3.8/ssl.py", line 1128, in read
112.5     return self._sslobj.read(len, buffer)
112.5 socket.timeout: The read operation timed out
112.5
112.5 During handling of the above exception, another exception occurred:
112.5
112.5 Traceback (most recent call last):
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
112.5     status = self.run(options, args)
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
112.5     resolver.resolve(requirement_set)
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
112.5     discovered_reqs.extend(self._resolve_one(requirement_set, req))
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
112.5     abstract_dist = self._get_abstract_dist_for(req_to_install)
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
112.5     abstract_dist = self.preparer.prepare_linked_requirement(req)
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
112.5     local_path = unpack_url(
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 282, in unpack_url
112.5     return unpack_http_url(
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 158, in unpack_http_url
112.5     from_path, content_type = _download_http_url(
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
112.5     for chunk in download.chunks:
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/utils/ui.py", line 160, in iter
112.5     for x in it:
112.5   File "/usr/lib/python3/dist-packages/pip/_internal/network/utils.py", line 15, in response_chunks
112.5     for chunk in response.raw.stream(
112.5   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/response.py", line 564, in stream
112.5     data = self.read(amt=amt, decode_content=decode_content)
112.5   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/response.py", line 529, in read
112.5     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
112.5   File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
112.5     self.gen.throw(type, value, traceback)
112.5   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/response.py", line 430, in _error_catcher
112.5     raise ReadTimeoutError(self._pool, None, "Read timed out.")
112.5 urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------
Dockerfile:18
--------------------
  16 |     RUN apt-get -y update
  17 |     RUN apt-get -y install git
  18 | >>> RUN pip install git+https://github.com/WildMeOrg/scoutbot.git
  19 |
  20 |     RUN pip3 uninstall -y onnxruntime
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install git+https://github.com/WildMeOrg/scoutbot.git" did not complete successfully: exit code: 2
```
I can confirm that in a separate env I can pip install scoutbot from that url, something about the dockerfile is problematic.

```
(test) benweinstein@Bens-MacBook-Pro scout % conda create python=3.10 --name scout
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/benweinstein/.conda/envs/scout

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h6c40b1e_5         151 KB
    ca-certificates-2024.3.11  |       hecd8cb5_0         128 KB
    openssl-3.0.13             |       hca72f7f_0         4.5 MB
    pip-23.3.1                 |  py310hecd8cb5_0         2.7 MB
    python-3.10.14             |       h5ee71fb_0        13.2 MB
    setuptools-68.2.2          |  py310hecd8cb5_0         959 KB
    tzdata-2024a               |       h04d1e81_0         116 KB
    wheel-0.41.2               |  py310hecd8cb5_0         110 KB
    xz-5.4.6                   |       h6c40b1e_0         373 KB
    ------------------------------------------------------------
                                           Total:        22.1 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h6c40b1e_5
  ca-certificates    pkgs/main/osx-64::ca-certificates-2024.3.11-hecd8cb5_0
  libffi             pkgs/main/osx-64::libffi-3.4.4-hecd8cb5_0
  ncurses            pkgs/main/osx-64::ncurses-6.4-hcec6c5f_0
  openssl            pkgs/main/osx-64::openssl-3.0.13-hca72f7f_0
  pip                pkgs/main/osx-64::pip-23.3.1-py310hecd8cb5_0
  python             pkgs/main/osx-64::python-3.10.14-h5ee71fb_0
  readline           pkgs/main/osx-64::readline-8.2-hca72f7f_0
  setuptools         pkgs/main/osx-64::setuptools-68.2.2-py310hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.41.2-h6c40b1e_0
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  wheel              pkgs/main/osx-64::wheel-0.41.2-py310hecd8cb5_0
  xz                 pkgs/main/osx-64::xz-5.4.6-h6c40b1e_0
  zlib               pkgs/main/osx-64::zlib-1.2.13-h4dc903c_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
tzdata-2024a         | 116 KB    | ######################################################################################################################################### | 100%
bzip2-1.0.8          | 151 KB    | ######################################################################################################################################### | 100%
setuptools-68.2.2    | 959 KB    | ######################################################################################################################################### | 100%
wheel-0.41.2         | 110 KB    | ######################################################################################################################################### | 100%
pip-23.3.1           | 2.7 MB    | ######################################################################################################################################### | 100%
openssl-3.0.13       | 4.5 MB    | ######################################################################################################################################### | 100%
ca-certificates-2024 | 128 KB    | ######################################################################################################################################### | 100%
xz-5.4.6             | 373 KB    | ######################################################################################################################################### | 100%
python-3.10.14       | 13.2 MB   | ######################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate scout
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(test) benweinstein@Bens-MacBook-Pro scout % conda activate scout
```

```
(scout) benweinstein@Bens-MacBook-Pro scout % pip install git+https://github.com/WildMeOrg/scoutbot.git
Collecting git+https://github.com/WildMeOrg/scoutbot.git
  Cloning https://github.com/WildMeOrg/scoutbot.git to /private/var/folders/5m/dmt63fq959jf1lgc58kz9w0h0000gn/T/pip-req-build-tg39zz26
  Running command git clone --filter=blob:none --quiet https://github.com/WildMeOrg/scoutbot.git /private/var/folders/5m/dmt63fq959jf1lgc58kz9w0h0000gn/T/pip-req-build-tg39zz26
  Resolved https://github.com/WildMeOrg/scoutbot.git to commit 9f6c53163ea340d7a8a00e6a053f87106ca1609f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from scoutbot==0.1.18)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting codecov (from scoutbot==0.1.18)
  Using cached codecov-2.1.13-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting coverage (from scoutbot==0.1.18)
....
(scout) benweinstein@Bens-MacBook-Pro scout % python
Python 3.10.14 (main, Mar 21 2024, 11:24:58) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
imp>>> import scoutbot
```

While the dev version is fixed, I can workaround and checkout scout from dockerhub.

**Comment by TanyaStere42** [comment] 2024-04-12 17:54
@bw4sz , we've done an initial pass and testing with this, and thing it was resolved by the change in #77 . If you're still receiving the error, let me know.

**Comment by bw4sz** [comment] 2024-04-12 21:15
Thanks I'll have a look.

**Comment by TanyaStere42** [comment] 2024-06-01 05:36
confirmed locally, cannot reproduce exception with the new changes

**Closed by TanyaStere42** 2024-06-01 05:36 UTC
